### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by Juan321654** [alexmacarthur/graphql-quest#3]
im trying the example `More Complicated Usage` but when i try to run the query i get a 
`ReferenceError: fetch is not defined
at n (C:\Users\juanc\Documents\Work\projects\to-delete-pi-server-heroku-working-dontdelete\node_modules\graphql-quest\dist\index.umd.js:1:874)
`

the error mentions this folder `graphql-quest/dist/index.es.js` and i see the fetch at line 35. 

any idea on what to do?

**Comment by alexmacarthur** [comment]
You're trying to use this in an environment that doesn't support `fetch` out of the box. You'll need to either use a more modern version of Node (like v18), or else install something like [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch).

https://github.com/alexmacarthur/graphql-quest#usage-in-node
